// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: envelope.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *MessageAck) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type WebSocketMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*WebSocketMessage_Payload
	//	*WebSocketMessage_Receipt
	//	*WebSocketMessage_Ack
	//	*WebSocketMessage_Gkd
	//	*WebSocketMessage_Gme
	Content       isWebSocketMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *WebSocketMessage) GetContent() isWebSocketMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WebSocketMessage) GetPayload() *EncryptedPayload {
	if x != nil {
		if x, ok := x.Content.(*WebSocketMessage_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

func (x *WebSocketMessage) GetReceipt() *DeliveryReceipt {
	if x != nil {
		if x, ok := x.Content.(*WebSocketMessage_Receipt); ok {
			return x.Receipt
		}
	}
	return nil
}

func (x *WebSocketMessage) GetAck() *MessageAck {
	if x != nil {
		if x, ok := x.Content.(*WebSocketMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *WebSocketMessage) GetGkd() *GroupKeyDistribution {
	if x != nil {
		if x, ok := x.Content.(*WebSocketMessage_Gkd); ok {
			return x.Gkd
		}
	}
	return nil
}

func (x *WebSocketMessage) GetGme() *GroupMembershipEvent {
	if x != nil {
		if x, ok := x.Content.(*WebSocketMessage_Gme); ok {
			return x.Gme
		}
	}
	return nil
}

type isWebSocketMessage_Content interface {
	isWebSocketMessage_Content()
}

type WebSocketMessage_Payload struct {
	Payload *EncryptedPayload `protobuf:"bytes,1,opt,name=payload,proto3,oneof"`
}

type WebSocketMessage_Receipt struct {
	Receipt *DeliveryReceipt `protobuf:"bytes,2,opt,name=receipt,proto3,oneof"`
}

type WebSocketMessage_Ack struct {
	Ack *MessageAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type WebSocketMessage_Gkd struct {
	Gkd *GroupKeyDistribution `protobuf:"bytes,4,opt,name=gkd,proto3,oneof"`
}

type WebSocketMessage_Gme struct {
	Gme *GroupMembershipEvent `protobuf:"bytes,5,opt,name=gme,proto3,oneof"`
}

func (*WebSocketMessage_Payload) isWebSocketMessage_Content() {}

func (*WebSocketMessage_Receipt) isWebSocketMessage_Content() {}

func (*WebSocketMessage_Ack) isWebSocketMessage_Content() {}

func (*WebSocketMessage_Gkd) isWebSocketMessage_Content() {}

func (*WebSocketMessage_Gme) isWebSocketMessage_Content() {}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\x02pb\x1a\rmessage.proto\x1a\vgroup.proto\"+\n" +
	"\n" +
	"MessageAck\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\x80\x02\n" +
	"\x10WebSocketMessage\x120\n" +
	"\apayload\x18\x01 \x01(\v2\x14.pb.EncryptedPayloadH\x00R\apayload\x12/\n" +
	"\areceipt\x18\x02 \x01(\v2\x13.pb.DeliveryReceiptH\x00R\areceipt\x12\"\n" +
	"\x03ack\x18\x03 \x01(\v2\x0e.pb.MessageAckH\x00R\x03ack\x12,\n" +
	"\x03gkd\x18\x04 \x01(\v2\x18.pb.GroupKeyDistributionH\x00R\x03gkd\x12,\n" +
	"\x03gme\x18\x05 \x01(\v2\x18.pb.GroupMembershipEventH\x00R\x03gmeB\t\n" +
	"\acontentB\x06Z\x04./pbb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_envelope_proto_goTypes = []any{
	(*MessageAck)(nil),           // 0: pb.MessageAck
	(*WebSocketMessage)(nil),     // 1: pb.WebSocketMessage
	(*EncryptedPayload)(nil),     // 2: pb.EncryptedPayload
	(*DeliveryReceipt)(nil),      // 3: pb.DeliveryReceipt
	(*GroupKeyDistribution)(nil), // 4: pb.GroupKeyDistribution
	(*GroupMembershipEvent)(nil), // 5: pb.GroupMembershipEvent
}
var file_envelope_proto_depIdxs = []int32{
	2, // 0: pb.WebSocketMessage.payload:type_name -> pb.EncryptedPayload
	3, // 1: pb.WebSocketMessage.receipt:type_name -> pb.DeliveryReceipt
	0, // 2: pb.WebSocketMessage.ack:type_name -> pb.MessageAck
	4, // 3: pb.WebSocketMessage.gkd:type_name -> pb.GroupKeyDistribution
	5, // 4: pb.WebSocketMessage.gme:type_name -> pb.GroupMembershipEvent
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	file_message_proto_init()
	file_group_proto_init()
	file_envelope_proto_msgTypes[1].OneofWrappers = []any{
		(*WebSocketMessage_Payload)(nil),
		(*WebSocketMessage_Receipt)(nil),
		(*WebSocketMessage_Ack)(nil),
		(*WebSocketMessage_Gkd)(nil),
		(*WebSocketMessage_Gme)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
