// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: group.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupMembershipEvent_Kind int32

const (
	GroupMembershipEvent_JOINED  GroupMembershipEvent_Kind = 0
	GroupMembershipEvent_LEFT    GroupMembershipEvent_Kind = 1
	GroupMembershipEvent_REMOVED GroupMembershipEvent_Kind = 2
)

// Enum value maps for GroupMembershipEvent_Kind.
var (
	GroupMembershipEvent_Kind_name = map[int32]string{
		0: "JOINED",
		1: "LEFT",
		2: "REMOVED",
	}
	GroupMembershipEvent_Kind_value = map[string]int32{
		"JOINED":  0,
		"LEFT":    1,
		"REMOVED": 2,
	}
)

func (x GroupMembershipEvent_Kind) Enum() *GroupMembershipEvent_Kind {
	p := new(GroupMembershipEvent_Kind)
	*p = x
	return p
}

func (x GroupMembershipEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupMembershipEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_group_proto_enumTypes[0].Descriptor()
}

func (GroupMembershipEvent_Kind) Type() protoreflect.EnumType {
	return &file_group_proto_enumTypes[0]
}

func (x GroupMembershipEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupMembershipEvent_Kind.Descriptor instead.
func (GroupMembershipEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{1, 0}
}

type GroupKeyDistribution struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupId           string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SenderUserId      string                 `protobuf:"bytes,2,opt,name=sender_user_id,json=senderUserId,proto3" json:"sender_user_id,omitempty"`
	SenderDeviceId    string                 `protobuf:"bytes,3,opt,name=sender_device_id,json=senderDeviceId,proto3" json:"sender_device_id,omitempty"`
	RecipientUserId   string                 `protobuf:"bytes,4,opt,name=recipient_user_id,json=recipientUserId,proto3" json:"recipient_user_id,omitempty"`
	RecipientDeviceId string                 `protobuf:"bytes,5,opt,name=recipient_device_id,json=recipientDeviceId,proto3" json:"recipient_device_id,omitempty"`
	EncryptedSkdm     []byte                 `protobuf:"bytes,6,opt,name=encrypted_skdm,json=encryptedSkdm,proto3" json:"encrypted_skdm,omitempty"`
	Nonce             []byte                 `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupKeyDistribution) Reset() {
	*x = GroupKeyDistribution{}
	mi := &file_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupKeyDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupKeyDistribution) ProtoMessage() {}

func (x *GroupKeyDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupKeyDistribution.ProtoReflect.Descriptor instead.
func (*GroupKeyDistribution) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{0}
}

func (x *GroupKeyDistribution) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupKeyDistribution) GetSenderUserId() string {
	if x != nil {
		return x.SenderUserId
	}
	return ""
}

func (x *GroupKeyDistribution) GetSenderDeviceId() string {
	if x != nil {
		return x.SenderDeviceId
	}
	return ""
}

func (x *GroupKeyDistribution) GetRecipientUserId() string {
	if x != nil {
		return x.RecipientUserId
	}
	return ""
}

func (x *GroupKeyDistribution) GetRecipientDeviceId() string {
	if x != nil {
		return x.RecipientDeviceId
	}
	return ""
}

func (x *GroupKeyDistribution) GetEncryptedSkdm() []byte {
	if x != nil {
		return x.EncryptedSkdm
	}
	return nil
}

func (x *GroupKeyDistribution) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type GroupMembershipEvent struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	GroupId       string                    `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Kind          GroupMembershipEvent_Kind `protobuf:"varint,2,opt,name=kind,proto3,enum=pb.GroupMembershipEvent_Kind" json:"kind,omitempty"`
	ActorId       string                    `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	SubjectId     string                    `protobuf:"bytes,4,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Timestamp     int64                     `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMembershipEvent) Reset() {
	*x = GroupMembershipEvent{}
	mi := &file_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembershipEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembershipEvent) ProtoMessage() {}

func (x *GroupMembershipEvent) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembershipEvent.ProtoReflect.Descriptor instead.
func (*GroupMembershipEvent) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMembershipEvent) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMembershipEvent) GetKind() GroupMembershipEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return GroupMembershipEvent_JOINED
}

func (x *GroupMembershipEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *GroupMembershipEvent) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GroupMembershipEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_group_proto protoreflect.FileDescriptor

const file_group_proto_rawDesc = "" +
	"\n" +
	"\vgroup.proto\x12\x02pb\"\x9a\x02\n" +
	"\x14GroupKeyDistribution\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12$\n" +
	"\x0esender_user_id\x18\x02 \x01(\tR\fsenderUserId\x12(\n" +
	"\x10sender_device_id\x18\x03 \x01(\tR\x0esenderDeviceId\x12*\n" +
	"\x11recipient_user_id\x18\x04 \x01(\tR\x0frecipientUserId\x12.\n" +
	"\x13recipient_device_id\x18\x05 \x01(\tR\x11recipientDeviceId\x12%\n" +
	"\x0eencrypted_skdm\x18\x06 \x01(\fR\rencryptedSkdm\x12\x14\n" +
	"\x05nonce\x18\a \x01(\fR\x05nonce\"\xe7\x01\n" +
	"\x14GroupMembershipEvent\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x121\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1d.pb.GroupMembershipEvent.KindR\x04kind\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x04 \x01(\tR\tsubjectId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\")\n" +
	"\x04Kind\x12\n" +
	"\n" +
	"\x06JOINED\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x01\x12\v\n" +
	"\aREMOVED\x10\x02B\x06Z\x04./pbb\x06proto3"

var (
	file_group_proto_rawDescOnce sync.Once
	file_group_proto_rawDescData []byte
)

func file_group_proto_rawDescGZIP() []byte {
	file_group_proto_rawDescOnce.Do(func() {
		file_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_group_proto_rawDesc), len(file_group_proto_rawDesc)))
	})
	return file_group_proto_rawDescData
}

var file_group_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_group_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_group_proto_goTypes = []any{
	(GroupMembershipEvent_Kind)(0), // 0: pb.GroupMembershipEvent.Kind
	(*GroupKeyDistribution)(nil),   // 1: pb.GroupKeyDistribution
	(*GroupMembershipEvent)(nil),   // 2: pb.GroupMembershipEvent
}
var file_group_proto_depIdxs = []int32{
	0, // 0: pb.GroupMembershipEvent.kind:type_name -> pb.GroupMembershipEvent.Kind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_group_proto_init() }
func file_group_proto_init() {
	if File_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_group_proto_rawDesc), len(file_group_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_group_proto_goTypes,
		DependencyIndexes: file_group_proto_depIdxs,
		EnumInfos:         file_group_proto_enumTypes,
		MessageInfos:      file_group_proto_msgTypes,
	}.Build()
	File_group_proto = out.File
	file_group_proto_goTypes = nil
	file_group_proto_depIdxs = nil
}
