// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_TEXT  MessageType = 0
	MessageType_IMAGE MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
	}
	MessageType_value = map[string]int32{
		"TEXT":  0,
		"IMAGE": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type ReceiptStatus int32

const (
	ReceiptStatus_DELIVERED ReceiptStatus = 0
	ReceiptStatus_READ      ReceiptStatus = 1
)

// Enum value maps for ReceiptStatus.
var (
	ReceiptStatus_name = map[int32]string{
		0: "DELIVERED",
		1: "READ",
	}
	ReceiptStatus_value = map[string]int32{
		"DELIVERED": 0,
		"READ":      1,
	}
)

func (x ReceiptStatus) Enum() *ReceiptStatus {
	p := new(ReceiptStatus)
	*p = x
	return p
}

func (x ReceiptStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReceiptStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (ReceiptStatus) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x ReceiptStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReceiptStatus.Descriptor instead.
func (ReceiptStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

type EncryptedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderShadeId string                 `protobuf:"bytes,3,opt,name=sender_shade_id,json=senderShadeId,proto3" json:"sender_shade_id,omitempty"`
	// 1-1 mesajlarda dolu, grup mesajlarında boş.
	ReceiverId     string      `protobuf:"bytes,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Ciphertext     []byte      `protobuf:"bytes,5,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Nonce          []byte      `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AuthTag        []byte      `protobuf:"bytes,7,opt,name=auth_tag,json=authTag,proto3" json:"auth_tag,omitempty"`
	Timestamp      int64       `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type           MessageType `protobuf:"varint,9,opt,name=type,proto3,enum=pb.MessageType" json:"type,omitempty"`
	GroupId        string      `protobuf:"bytes,10,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SenderDeviceId string      `protobuf:"bytes,11,opt,name=sender_device_id,json=senderDeviceId,proto3" json:"sender_device_id,omitempty"`
	SenderKeyId    uint32      `protobuf:"varint,12,opt,name=sender_key_id,json=senderKeyId,proto3" json:"sender_key_id,omitempty"`
	ChainIndex     uint64      `protobuf:"varint,13,opt,name=chain_index,json=chainIndex,proto3" json:"chain_index,omitempty"`
	Signature      []byte      `protobuf:"bytes,14,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EncryptedPayload) Reset() {
	*x = EncryptedPayload{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedPayload) ProtoMessage() {}

func (x *EncryptedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedPayload.ProtoReflect.Descriptor instead.
func (*EncryptedPayload) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedPayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EncryptedPayload) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *EncryptedPayload) GetSenderShadeId() string {
	if x != nil {
		return x.SenderShadeId
	}
	return ""
}

func (x *EncryptedPayload) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *EncryptedPayload) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptedPayload) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedPayload) GetAuthTag() []byte {
	if x != nil {
		return x.AuthTag
	}
	return nil
}

func (x *EncryptedPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EncryptedPayload) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TEXT
}

func (x *EncryptedPayload) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *EncryptedPayload) GetSenderDeviceId() string {
	if x != nil {
		return x.SenderDeviceId
	}
	return ""
}

func (x *EncryptedPayload) GetSenderKeyId() uint32 {
	if x != nil {
		return x.SenderKeyId
	}
	return 0
}

func (x *EncryptedPayload) GetChainIndex() uint64 {
	if x != nil {
		return x.ChainIndex
	}
	return 0
}

func (x *EncryptedPayload) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type DeliveryReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderShadeId string                 `protobuf:"bytes,3,opt,name=sender_shade_id,json=senderShadeId,proto3" json:"sender_shade_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Status        ReceiptStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=pb.ReceiptStatus" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	GroupId       string                 `protobuf:"bytes,7,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryReceipt) Reset() {
	*x = DeliveryReceipt{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryReceipt) ProtoMessage() {}

func (x *DeliveryReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryReceipt.ProtoReflect.Descriptor instead.
func (*DeliveryReceipt) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryReceipt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeliveryReceipt) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *DeliveryReceipt) GetSenderShadeId() string {
	if x != nil {
		return x.SenderShadeId
	}
	return ""
}

func (x *DeliveryReceipt) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *DeliveryReceipt) GetStatus() ReceiptStatus {
	if x != nil {
		return x.Status
	}
	return ReceiptStatus_DELIVERED
}

func (x *DeliveryReceipt) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeliveryReceipt) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x02pb\"\xd3\x03\n" +
	"\x10EncryptedPayload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12&\n" +
	"\x0fsender_shade_id\x18\x03 \x01(\tR\rsenderShadeId\x12\x1f\n" +
	"\vreceiver_id\x18\x04 \x01(\tR\n" +
	"receiverId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x05 \x01(\fR\n" +
	"ciphertext\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\fR\x05nonce\x12\x19\n" +
	"\bauth_tag\x18\a \x01(\fR\aauthTag\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12#\n" +
	"\x04type\x18\t \x01(\x0e2\x0f.pb.MessageTypeR\x04type\x12\x19\n" +
	"\bgroup_id\x18\n" +
	" \x01(\tR\agroupId\x12(\n" +
	"\x10sender_device_id\x18\v \x01(\tR\x0esenderDeviceId\x12\"\n" +
	"\rsender_key_id\x18\f \x01(\rR\vsenderKeyId\x12\x1f\n" +
	"\vchain_index\x18\r \x01(\x04R\n" +
	"chainIndex\x12\x1c\n" +
	"\tsignature\x18\x0e \x01(\fR\tsignature\"\xfa\x01\n" +
	"\x0fDeliveryReceipt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12&\n" +
	"\x0fsender_shade_id\x18\x03 \x01(\tR\rsenderShadeId\x12\x1f\n" +
	"\vreceiver_id\x18\x04 \x01(\tR\n" +
	"receiverId\x12)\n" +
	"\x06status\x18\x05 \x01(\x0e2\x11.pb.ReceiptStatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bgroup_id\x18\a \x01(\tR\agroupId*\"\n" +
	"\vMessageType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01*(\n" +
	"\rReceiptStatus\x12\r\n" +
	"\tDELIVERED\x10\x00\x12\b\n" +
	"\x04READ\x10\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_proto_goTypes = []any{
	(MessageType)(0),         // 0: pb.MessageType
	(ReceiptStatus)(0),       // 1: pb.ReceiptStatus
	(*EncryptedPayload)(nil), // 2: pb.EncryptedPayload
	(*DeliveryReceipt)(nil),  // 3: pb.DeliveryReceipt
}
var file_message_proto_depIdxs = []int32{
	0, // 0: pb.EncryptedPayload.type:type_name -> pb.MessageType
	1, // 1: pb.DeliveryReceipt.status:type_name -> pb.ReceiptStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
